# Generated by Django 3.2.18 on 2023-05-01 08:54

import blango_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blango_auth', '0002_auto_20230430_1057'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', blango_auth.models.BlangoUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
